version: "3"

services:
  nginx:
    image: skpr/nginx:1.x
    ports:
      - 8080:8080
    volumes:
      - .:/data

  php-fpm:
    image: skpr/php-fpm:7.2-1.x
    volumes:
      - .:/data

  php-cli:
    image: skpr/php-cli:7.2-1.x
    volumes:
      - .:/data

  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=local
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
