version: "3"

services:

  ##################
  # Web
  ##################

  nginx:
    image: skpr/nginx:1.x-dev
    ports:
      - 8080:8080
      - 3306:3306
    volumes:
      - data:/data
      - ./app/sites/default/files:/data/app/sites/default/files

  php-fpm: &php-fpm
    image: skpr/php-fpm:7.3-1.x-dev
    network_mode: service:nginx
    volumes:
      - data:/data
      - ./app/sites/default/files:/data/app/sites/default/files

  php-fpm-xdebug:
    <<: *php-fpm
    image: skpr/php-fpm:7.3-1.x-xdebug
    environment:
      - PHP_FPM_PORT=9001
      - PHP_IDE_CONFIG=serverName=localhost

  ##################
  # CLI
  ##################

  php-cli: &php-cli
    image: skpr/php-cli:7.3-1.x-dev
    network_mode: service:nginx
    volumes:
      - data:/data
      - ./app/sites/default/files:/data/app/sites/default/files

  php-cli-xdebug:
    <<: *php-cli
    image: skpr/php-cli:7.3-1.x-xdebug
    environment:
      - PHP_IDE_CONFIG=serverName=localhost

  frontend:
    image: skpr/node:10-1.x
    network_mode: service:nginx
    volumes:
      - data:/data
      - ./app/sites/default/files:/data/app/sites/default/files

  ##################
  # Databases
  ##################

  mysql-default:
    # For "skpr2 mysql pull dev" to get the latest image.
    image: xxxxxxxx.dkr.ecr.ap-southeast-2.amazonaws.com/skpr-pnx-example/mysql:dev-default-latest
    network_mode: service:nginx

  ##################
  # Services
  ##################

  mailhog:
    image: mailhog/mailhog
    network_mode: service:nginx
    ports:
      - 8025:8025

volumes:
  data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}
