# Size of the environment being deployed.
# https://docs.skpr.io/size
# This is configurable profile.
size: "small"

# Services are technologies which complement your standard deployment stack.
services:
  mysql:
    default:
      class: nonprod
      image:
        schedule: "* * * * *"

  # Solr provides advanced search functionality.
  # https://docs.skpr.io/addon/solr
  # solr:
  #   core1:
  #     version: "5.x"
  #   core2:
  #     version: "5.x"

# Crons are background tasks which allow for large tasks to be
# executed outside of a web request.
# These tasks will execute the "cli" container.
cron:
  # Standard Drupal cron execution.
  drush:
    command:  "drush cron"
    schedule: "@hourly"

  # Processing mail via a queue allows faster web request response times
  # and more resiliant mail delivery.
  # https://docs.skpr.io/drupal/smtp
  mail:
    command:  "drush mail-queue"
    schedule: "*/5 * * * *"

# @todo, Make these defaults of the stack.
ingress:
  cookies:
   - SESS*
   - SSESS*
  headers:
   - Accept
   - Authorization
   - CloudFront-Forwarded-Proto
   - Host
   - User-Agent

smtp:
  from:
    address: nick@previousnext.com.au

backup:
  schedule: "@daily"
