# Provides both hosting and developers with an identifier for if
# an environment is used for production.
#  eg. Rollout MySQL updates to all non production environments before
#      upgrading production
production: true

ingress:
  - "www.example.com"
  # Ingress can also be configured to expose this application
  # on a subpath, this is useful for API based endpoints which
  # need to be exposed to a frontend.
  # - "www.example.com/api"

# Size of the environment being deployed.
# https://docs.skpr.io/size
size: "medium"
